services:
  evc:
    container_name: evc
    build: .
    ports:
      - "51223:5788"
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - evc

networks:
  evc:
    name: evc
    driver: bridge
    external: false
